export const prompts: string[] = [
    "Describe your ideal weekend getaway in vivid detail—where would you go, who would be with you, and what would you do?",
    "Use only ASCII characters to sketch a happy or silly face that reflects your mood right now.",
    "What’s one food you could eat every day for the rest of your life, and what makes it so special to you?",
    "Name your best friend and describe one unforgettable memory you share that still makes you smile today.",
    "Write a four-line poem about the sound of rain hitting a window during a quiet evening.",
    "Tell a strange or little-known fact that could surprise most people—something weird, funny, or mind-blowing.",
    "How would you explain the color blue to someone who has never seen it? Use emotions, metaphors, or sensations.",
    "List three hobbies or activities that bring you peace and help you recharge after a stressful day.",
    "If a magical genie gave you one wish—but it can't be for money or fame—what would you wish for and why?",
    "Share a dream you've had that felt incredibly real or meaningful, and explain why it stuck with you.",
    "Invent a short story about a mysterious object you found in the forest that changes reality when touched.",
    "Describe what happiness looks, sounds, and feels like to you in one short paragraph.",
    "Invent a new fruit: what does it taste like, look like, and what strange powers might it have?",
    "If you could travel anywhere with anyone, living or dead, where would you go and what would you do together?",
    "Write a haiku about silence in a busy world—use nature as inspiration.",
    "Share a fact that sounds fake but is actually true—something scientific, historical, or just wild.",
    "Describe the color green without using the word 'green'—focus on comparisons, feelings, and nature.",
    "List three hobbies you'd love to try if time, money, and skill weren’t an issue.",
    "Make a heartfelt wish for something the world truly needs, beyond your own life.",
    "Recall a dream that made you laugh, cry, or think deeply the next day—what happened in it?",
    "Imagine Earth lost all gravity for one minute. What chaos or funny events might happen around you?",
    "Use only text symbols to draw your favorite emoji or invent a brand new one.",
    "What’s your go-to comfort food and the memory or feeling it brings every time you eat it?",
    "Describe your childhood best friend and how they influenced who you are today.",
    "Write a short, magical poem about the night sky and what might be hiding behind the stars.",
    "Share a fun historical fact you think everyone should know—bonus points if it’s bizarre.",
    "Explain what the color red feels like emotionally and physically, as if words were all you had.",
    "If you could automate one hobby or chore, which one would it be and what would you do with that time?",
    "If you could pause time for just one hour each day, how would you use it and why?",
    "Describe a dream so beautiful or strange that you'd love to live in it again, even if only briefly.",
    "Imagine you found a door in your room that leads to another universe—what’s on the other side?",
    "Write a letter to your future self 10 years from now—what advice, hopes, or questions would you share?",
    "Describe a sound that always brings back a specific memory—what’s the sound and the memory?",
    "If you could bring one extinct creature back to life, which would it be and why?",
    "Invent a holiday that the whole world celebrates—what’s its purpose, traditions, and name?",
    "What’s a small act of kindness you experienced that left a lasting impact on you?",
    "Imagine you’re a detective in a city where magic is real—what’s your first case?",
    "Describe a moment in your life when you felt truly fearless—what happened?",
    "Write a short scene where a robot learns how to feel emotions for the first time.",
    "If you could speak to one historical figure for 10 minutes, who would it be and what would you ask?",
];
