
services:
  postgresql:
    image: postgres:17.3-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi-db
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - ../../volumes/pgdata:/var/lib/postgresql/data

  # postgres-test:
  #   image: postgres:17.3-alpine3.21
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password123
  #     POSTGRES_DB: db-test
  #   ports:
  #     - "5431:5432"
  #   volumes:
  #     - ./postgresql-test:/var/lib/postgresql/data
  

networks:
  postgres_network:
    driver: bridge

volumes:
  pgadmin_data: